### ISSUE TITLE
Support for extending promises

### ISSUE THREAD

**Issue by wlandau** [rstudio/promises#103]
[`mirai`](https://github.com/shikokuchuo/mirai) and [`crew`](https://github.com/wlandau/crew) are new packages for distributed distributed computing similar to `future`. They can both leverage their parallel computing capabilities to create custom promise objects, as described at <https://shikokuchuo.net/mirai/articles/promises.html> for `mirai` and at <https://wlandau.github.io/crew/articles/promises.html>  for `crew` (also c.f. https://github.com/wlandau/crew/issues/147, https://github.com/wlandau/crew/pull/149). The promises seem to work, but they do rely on [polling with `later::later()`](https://github.com/shikokuchuo/mirai/blob/2c7600c63a2c5bd9f29e4aa574dd787f9cdca51a/R/promises.R#L53-L62), which may not be as efficient or as kind to the CPU as a truly event-driven approach.

It would be great if `promises` could provide a general solution for triggering callbacks asynchronously, or if the documentation could describe how to implement a successful event-driven pattern. I am not sure if anything like this currently exists, but there may be possibilities using the [`nanonext`](https://github.com/shikokuchuo/nanonext) package. [`nanonext`](https://github.com/shikokuchuo/nanonext) is a low-level R client for the [NNG messaging library](https://nng.nanomsg.org), which in turn provides network protocols, asynchronous I/O, and perhaps most importantly for this issue, synchronization primitives such as condition variables which can be configured to respond to local network events.

This thread is part of a follow-up on recent conversations with @shikokuchuo and @jcheng5.

**Comment by shikokuchuo** [comment]
I think I've figured a way of implementing this completely event-driven approach by polling read activity on file descriptors internal to NNG sockets – plugging into R’s event handlers similar to `later`. I’ve touched on this with @wlandau already, @jcheng5 happy to discuss with you whenever you wish.
