### ISSUE TITLE
Update Shiny installation readme

### ISSUE THREAD

**Issue by MarkEdmondson1234** [rstudio/promises#14]
Hello, I tried to install from Shiny as per the readme and its now a 404:

```r
devtools::install_github("rstudio/shiny@async")
#Downloading GitHub repo rstudio/shiny@async from URL https://api.github.com/repos/rstudio/shiny/zipball/async
#Installation failed: 404: Not Found (404)
```

Is it on the main Shiny branch now?

**Comment by YsoSirius** [comment]
Since shiny 1.1.0 there is support for async operations. ([News](https://github.com/rstudio/shiny/blob/master/NEWS.md#shiny-110 ))

So yes, its on the main branch.

**Comment by MarkEdmondson1234** [comment]
Thanks!
