### ISSUE TITLE
Error passing packages to future_promises in combination with on.exit(plan(oplan)) [shiny]

### ISSUE THREAD

**Issue by CarlijnB** [rstudio/promises#93]
Hi, 

I'm developing a shiny app as an R package ("movenetapp") that includes several functions.
I'm trying to apply a movenetapp function in parallel to a number of different datasets, while updating progress bars. Having used @schloerke 's code [here](https://github.com/rstudio/shiny/issues/2196#issuecomment-1016858715 ), I ended up with mostly-functional code. 

However, things go wrong when I want to ensure all workers are closed, and any previous plan reinstated, upon exit/error.
When adding  `on.exit(plan(oplan), add = TRUE)` within the observeEvent, I get this persistent error:
`Error in execCallbacks(timeoutSecs, all, loop$id) :  Evaluation error: object of type 'closure' is not subsettable.`

Having tried to produce a reprex, I have identified that the error seems to relate to environments / passing a package to future_promise. I'll add a reply below with potential reprex and what seems to solve the issue.

**I would appreciate any advice as to how I could solve this in my real code**, where it involves a complex function that's defined in its own file.

Current code (a little simplified) - this works if on.exit is commented-out, but raises error if on.exit is left in:

```
observeEvent(input$create_networks, {
        oplan <- plan("multisession")
        #on.exit(plan(oplan), add = TRUE)

        nw_count <- 0 #to keep track of networks created, for progress bar
        n <- length(selected_datasets())

        seq_len(n) %>%
          lapply(FUN = function(i) {
            df <- selected_datasets()[[i]]
            future_promise({movenetapp::movedata2networkDynamic(df)}, 
                           globals = c("df"),
                           envir = environment(),
                           seed = TRUE
                           ) %>%
              then(function(nw){ networks[[names(selected_datasets()[i])]] <- nw }) %>%
              finally(function(){
                nw_count <<- nw_count + 1
                updateProgressBar(session, "create_networks_pb",
                                  value = nw_count, total = n,
                                  range_value = c(0, n),
                                  title = "Generating networks...")})
          }) 
       })
```

**Comment by CarlijnB** [comment]
The reprex below works with EITHER the on.exit, OR the packages argument- but raises the same error when using both. 

Solution for reprex: defining fake_function within the lapply loop (below `df <- mdatasets[[i]]`) solves the issue, as the function is defined in the calling environment (?). 

But for my real code, how do I refer to a complex function that's defined in its own file, without raising the error? simply redefining within lapply didn't seem to do the job...

**Reprex**
```
library("tibble")
library("shiny")
library("promises")
library("future")
library("shinyWidgets")

mdatasets <- list(
  dataset_1 = tibble(x = 1:5, y = x * 2),
  dataset_2 = tibble(x = 1:5, y = x ^ 2),
  dataset_3 = tibble(x = 1:5, y = x + 2)
)
rv <- reactiveValues()
fake_function <- function(data){data*5}

ui <- fluidPage(
  actionButton("create_networks", "Generate networks"),
  progressBar("create_networks_pb", value = 0, display_pct = TRUE)
  )

server <- function(input, output, session){

  observeEvent(input$create_networks, {

    old_plan <- plan(multisession)
    #on.exit(plan(old_plan), add = TRUE) #removing this, takes the error away

    n <- length(mdatasets)
    seq_len(n) %>%
      lapply(FUN = function(i) {
        df <- mdatasets[[i]]
        future_promise({ fake_function(df) },
                       globals = c("df", "fake_function"),
                       #envir = environment(),
                       packages = "tibble" #tibble not needed, but illustrates that including this argument raises the error
                       ) %>%
          then(function(r){ rv[[names(mdatasets)[i]]] <- r
          }) %>%
          finally(function(){
            updateProgressBar(session, "create_networks_pb", value = i)
            })
        })
  })

}

shinyApp(ui, server)

```

**Comment by schloerke** [comment]
Why are you trying to set the plan within the observeEvent call?

Could you just call it outside the `server` function?

**Comment by CarlijnB** [comment]
@schloerke thank you for the suggestion - should on.exit work then? I mean, if the app closes down or raises an error, is the plan reset to the default?

**Comment by schloerke** [comment]
Are you trying to support multiple plans within the same app?

**Comment by CarlijnB** [comment]
I had originally thought of letting users select the number of threads to use for each process separately.
But that's not essential and I'd be fine taking that out.
I'm more worried about:

- implications of setting users' "plan", for their other activities in R - doesn't it work like a global option? 
- keeping users' cores engaged by not explicitly closing worker processes down (I read somewhere that on Windows that might happen?)

**Comment by schloerke** [comment]
> implications of setting users' "plan", for their other activities in R - doesn't it work like a global option?

Yes, it is globally set within the same R session. This will be applied to all users sessions on the same R session.

> keeping users' cores engaged by not explicitly closing worker processes down (I read somewhere that on Windows that might happen?)

I haven't heard of this (doesn't mean it doesn't exist), but I would not specifically safe guard against it. This seems like a `{future}` bug.


-------------------------------

All that being said, let's restructure the approach and capture the original plan earlier and restore it later:

* If you have access to how shiny's run method...
  * `shiny::runApp()` is serial and will always block. No matter how the app quits, the previous plan is restored. 
  * Within the app, feel free to set as many plans as you want with no need for any `on.exit` calls to restore a previous plan. (The important part is you are restoring the original previous plan when the app exits.)

```r
app <- func_to_make_app() # Ex: shiny::shinyApp(ui, server)

local({
  # Get the previous plan
  oplan <- future::plan()
  # Restore the plan when the local block exits
  on.exit({ future::plan(oplan) })

  # Run app
  shiny::runApp(app)  
})
```


* I do not recommend your current approach if there could be multiple users on the same app server. (Such as being hosted on shinyapps.io)
	* Ex: User A sets the future plan for the R session and starts doing long tasks. User B sets the future plan for the same R session and starts doing long tasks. User A is now working within User B's future plan.

--------------------------

Recap:
* If you are making an R package, I'd add a "run app" method so that you can control how the plan is started and restored. Set the plan before starting the app and restore the previous plan when exiting your run method.
* I would not set individual plans per user / interaction as it is not safe from other users / interactions.

**Comment by CarlijnB** [comment]
That makes sense, thank you very much for your excellent (and quick!) advice @schloerke !
